### ISSUE TITLE
No display of the tweet "in reply to" 

### ISSUE THREAD

**Issue by Agnes-** [mariotaku/twidere#238]
When I have a tweet replying to another one, there is an option 'in reply to" to see the original tweet. Since the last update, I cannot see the original tweet anymore. 
When I click on "in reply to", the tweet displays for less than a second and disapear. I tried several times with the same tweet and with several tweets and I have always the same result.
Could you please help?
Best
Agnes

**Comment by mariotaku** [comment]
Fixed.

**Comment by todestoast** [comment]
I am sorry to inform you that I am experiencing this problem, too in 0.3.0-dev-google and the only way to solve the problem for me was disabling auto refresh on start as mentioned above. Seems like the issue isn't fixed or am I on an old version, which I hop I am not?

**Comment by mkody** [comment]
@todestoast If you're using the Play version, it isn't fixed. (Last update `14 Nov 2014`, when mariotaku says "fixed" on 7 Jan.).

If really needed, you can get the _very latest/instable_ version [here, on mariotaku's dropbox.](https://www.dropbox.com/sh/q8cji9g6lal4f03/AADf61xi5k1YPaRsJPDmFg5ma)

**Comment by todestoast** [comment]
Hey, 

Thanks for the fast response. It's not that important for me I just thought, you'd be thinking it's fixed, while it wasn't. So I just wait for the update :)
